version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      
  build_docker_image:
    docker:
      - image: docker:24.0.5
    steps:
      - checkout
      - run:  
          name: Install Git  
          command: |  
            apk add --no-cache git  
      - setup_remote_docker:
          docker_layer_caching: false
      - run:  
          name: Build Docker Image  
          command: |   
            docker build -t guhan33/my-app-image:1.0 .  
      - run:  
          name: Login to Docker Hub  
          command: |  
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin  
      - run:  
          name: Push Docker Image  
          command: |  
           docker push guhan33/my-app-image:1.0 

workflows:
  build_and_test:
    jobs:
      - run_tests
      - build_docker_image:
          requires:
            - run_tests