version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      
  build_docker_image:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            export TAG=$(echo $CIRCLE_SHA1 | cut -c1-8)
            docker build -t my-app-image:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push my-app-image:$TAG

workflows:
  build_and_test:
    jobs:
      - run_tests
      - build_docker_image:
          requires:
            - run_tests